### ISSUE TITLE
README.mdの誤記

### ISSUE THREAD

**Issue by sakai00kou** [yamaha-network/ansible-collection-rtx#4]
# 問題
`README.md`に記載されている以下パラメータ、オプションが誤っているようなので確認して頂きたいです。

`match`パラメータの`lines`オプション→`line`が正しいかと思います。
`source`パラメータ→`src`が正しいかと思います。

**Comment by ymhogw** [comment]
上記コミットで対応させていただきました。本件クローズとさせていただきます。
